import{a as h,S,i}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const w="48820894-4cea1e59d649a954e9231553f",$="https://pixabay.com/api/";async function b(t,o=1,n=40){const s=`${$}?key=${w}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${n}`,e=await h.get(s);return{images:e.data.hits,total:e.data.totalHits}}const L=document.querySelector(".gallery");let q=new S(".gallery a");function v(t){const o=t.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:a,comments:p,downloads:g})=>`<li class="gallery-item">
      <a href="${s}" class="gallery-link">
        <img src="${n}" alt="${e}" />
        <div class="info">
          <p>Likes: ${r}</p>
          <p>Views: ${a}</p>
          <p>Comments: ${p}</p>
          <p>Downloads: ${g}</p>
        </div>
      </a>
      </li>`).join("");L.insertAdjacentHTML("beforeend",o),q.refresh()}const P=document.querySelector(".search-form"),y=document.querySelector(".loader"),I=document.querySelector(".gallery"),l=document.querySelector(".load-more");let u="",c=1;const m=40;let d=0;P.addEventListener("submit",async t=>{if(t.preventDefault(),u=t.target.elements.query.value.trim(),!u){i.warning({message:"Please enter a search query!"});return}O(),await f()});l.addEventListener("click",async()=>{c+=1,await f()});async function f(){y.style.display="block";try{const{images:t,total:o}=await b(u,c,m);if(d=o,t.length===0){i.error({message:"Sorry, no images found. Please try again!"});return}v(t),c*m>=d?(l.style.display="none",i.info({message:"We're sorry, but you've reached the end of search results."})):l.style.display="block",A()}catch{i.error({message:"Something went wrong. Please try again later."})}finally{y.style.display="none"}}function O(){I.innerHTML="",c=1,d=0,l.style.display="none"}function A(){var o;const t=((o=document.querySelector(".gallery-item"))==null?void 0:o.getBoundingClientRect().height)||0;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
