import{a as g,S as L,i as w}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();let l=1;const P=40;function b(){l=1}function v(){l+=1}async function S(o){const t="48621636-2f551eda37f80f5c324cc68cd",s=`https://pixabay.com/api/?${new URLSearchParams({key:t,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:l,per_page:P})}`;try{return(await g.get(s)).data}catch(e){throw new Error(`An error occurred: ${e.message}`)}}const $=document.querySelector(".gallery"),q=new L(".gallery a",{captionsData:"alt",captionDelay:250});function x(o){const{hits:t}=o,i=t.map(s=>{const{largeImageURL:e,webformatURL:r,tags:a,likes:f,views:p,comments:h,downloads:y}=s;return`
        <li class="gallery-item">
          <a href="${e}" class="gallery-link">
            <img src="${r}" alt="${a}" />
            <div class="info">
              <p>Likes: ${f}</p>
              <p>Views: ${p}</p>
              <p>Comments: ${h}</p>
              <p>Downloads: ${y}</p>
            </div>
          </a>
        </li>`}).join("");$.insertAdjacentHTML("beforeend",i),q.refresh()}const E=document.querySelector(".gallery"),n=document.querySelector(".load-more"),O=document.querySelector(".search-form"),d=document.querySelector(".search-input");let u="";n.classList.add("hide");O.addEventListener("submit",async o=>{o.preventDefault();const t=d.value.trim();if(!t){c("Sorry, there are no images matching your search query. Please try again!");return}u=t,E.innerHTML="",b(),n.classList.add("hide"),await m(u),d.value=""});n.addEventListener("click",async()=>{v(),await m(u)});async function m(o){try{const t=await S(o);if(t.hits.length===0&&t.totalHits===0){c("Sorry, there are no images matching your search query. Please try again!");return}x(t),t.hits.length<40||t.hits.length+(l-1)*40>=t.totalHits?(n.classList.add("hide"),c("We're sorry, but you've reached the end of search results.")):n.classList.remove("hide")}catch(t){c(t.message)}}function c(o){w.error({message:o})}
//# sourceMappingURL=index.js.map
