import{i as l,S as q,a as v}from"./assets/vendor-DEenWwFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const u=document.querySelector(".gallery"),b=document.querySelector(".loader"),P=document.querySelector(".load-more");function f(o){const r=o.querySelector(".loading-text"),n=o.querySelector(".loader");r&&r.remove(),n&&n.remove(),P.classList.remove("hide")}function w(o){const{hits:r}=o;if(r.length===0){l.error({message:"Sorry, there are no images matching your search query. Please, try again!"}),u.innerHTML="";return}const n=r.map(e=>{const{largeImageURL:t,webformatURL:a,tags:i,likes:y,views:h,comments:L,downloads:S}=e;return`
        <li class="gallery-item">
          <a href="${t}" class="gallery-link">
            <img src="${a}" alt="${i}" />
            <div class="info">
              <p>Likes: ${y}</p>
              <p>Views: ${h}</p>
              <p>Comments: ${L}</p>
              <p>Downloads: ${S}</p>
            </div>
          </a>
        </li>`}).join(" ");f(b),u.insertAdjacentHTML("beforeend",n),new q(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const $=document.querySelector(".gallery"),d=document.querySelector(".loader"),M=document.querySelector(".load-more");let s=1,m=40;function x(){s=1}function H(){s+=1}function O(o){f(o),o.insertAdjacentHTML("beforeend","<p>We're sorry, but you've reached the end of search results .</p>"),M.classList.add("hide")}async function g(o){const r="48621636-2f551eda37f80f5c324cc68cd",n=encodeURIComponent(o),e=`https://pixabay.com/api/?${new URLSearchParams({key:r,q:n,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:m})}`;try{const{data:t}=await v.get(e);if(w(t),t.totalHits<s*m){O(d);return}if(s>=2){const i=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:i.height*2,behavior:"smooth"})}}catch(t){console.error(t),$.innerHTML="",d.innerHTML="",l.error({message:"Something went wrong. Please try again later."});return}}const T=document.querySelector(".gallery"),R=document.querySelector(".load-more"),B=document.querySelector(".search-form"),p=document.querySelector(".search-input");B.addEventListener("submit",o=>{o.preventDefault();let r=p.value.trim();if(!r){l.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}T.innerHTML="",x(),g(r)});R.addEventListener("click",o=>{let r=p.value.trim();H(),g(r)});
//# sourceMappingURL=index.js.map
